import os

# ── Paths ────────────────────────────────────────────────────────────────────
BASE_DIR = os.environ.get("IRP_BASE_DIR", "/iridisfs/home/ao1g22/comp6228/irp")
TFDS_DIR = os.path.join(BASE_DIR, "tfds_data")
ART_DIR  = os.path.join(BASE_DIR, "artifacts")
OUT_DIR  = os.path.join(BASE_DIR, "outputs")

for _d in (ART_DIR, OUT_DIR):
    os.makedirs(_d, exist_ok=True)

# ── Shapes3D ──────────────────────────────────────────────────────────────────
# Generative factors used to GROUP images into orientation sequences.
# Each unique combination of GROUP_FACTORS defines one episode (sequence).
# SEQ_FACTOR is what varies within the episode (smooth temporal structure).
GROUP_FACTORS = ["floor_hue", "wall_hue", "object_hue", "scale", "shape"]
SEQ_FACTOR    = "orientation"
SEQ_LENGTH    = 15      # exactly 15 orientation steps per group

# Factors we probe for AFTER consolidation — ground-truth labels for evaluation.
# Crucially these are held out from the training objective; neither student is
# told what shape/colour etc. the object is.
PROBE_FACTORS = {
    "shape":       4,
    "floor_hue":  10,
    "wall_hue":   10,
    "object_hue": 10,
    "scale":       8,
    # Including orientation lets us distinguish the tautological effect
    # (sequential training makes orientation more decodable — expected) from
    # the non-tautological claim (static factors also improve — the finding).
    "orientation": 15,
}

N_TRAIN_GROUPS = 4000   # groups used for training  (each has 15 frames)
N_TEST_GROUPS  = 1000   # held-out groups for probing

# ── Model ─────────────────────────────────────────────────────────────────────
LATENT_DIM = 32
BATCH_SIZE = 32
IMG_SHAPE  = (64, 64, 3)   # Shapes3D native resolution

# ── Teacher training ──────────────────────────────────────────────────────────
TEACHER_EPOCHS = 40

# ── Student training ──────────────────────────────────────────────────────────
STUDENT_EPOCHS = 30

# ── IID replay (Spens & Burgess baseline) ─────────────────────────────────────
# Latent-space ContinuousHopfield: store teacher latents, query with noise,
# retrieve clean latent, decode → IID replay frame. Student trains on these
# decoded images with a reconstruction (VAE) objective.
N_IID_REPLAY  = 8000
BETA_MHN      = 100.0
MHN_NOISE_STD = 0.3

# ── Sequential replay (ours) ──────────────────────────────────────────────────
# Heteroassociative K/V Hopfield: K[i] = z_t, V[i] = z_{t+1} for every
# consecutive pair in every training sequence. Chains are generated by
# following the K/V memory forward. Student trains on decoded consecutive
# pairs with a next-frame prediction objective.
N_CHAINS     = 400
CHAIN_LENGTH = 15    # matches SEQ_LENGTH so chains mirror real episodes
BETA_KV      = 60.0
TOPK         = 50

# ── Multi-seed ────────────────────────────────────────────────────────────────
SEEDS = [0, 7, 42]

# ── Artifact paths ────────────────────────────────────────────────────────────
TEACHER_ENC_PATH = os.path.join(ART_DIR, "teacher_encoder.keras")
TEACHER_DEC_PATH = os.path.join(ART_DIR, "teacher_decoder.keras")
K_PATH           = os.path.join(ART_DIR, "K.npy")
V_PATH           = os.path.join(ART_DIR, "V.npy")


def student_paths(seed: int) -> dict:
    return {
        # Primary IID condition: same frames as sequential, shuffled order.
        # This is the fair apples-to-apples comparison.
        "iid_enc":      os.path.join(ART_DIR, f"student_iid_encoder_s{seed}.keras"),
        "iid_dec":      os.path.join(ART_DIR, f"student_iid_decoder_s{seed}.keras"),
        # Secondary IID condition: MHN-retrieved frames (Spens & Burgess model).
        # Different frame distribution — kept for reference only.
        "iid_mhn_enc":  os.path.join(ART_DIR, f"student_iid_mhn_encoder_s{seed}.keras"),
        "iid_mhn_dec":  os.path.join(ART_DIR, f"student_iid_mhn_decoder_s{seed}.keras"),
        # Sequential (ours).
        "seq_enc":      os.path.join(ART_DIR, f"student_seq_encoder_s{seed}.keras"),
        "seq_dec":      os.path.join(ART_DIR, f"student_seq_decoder_s{seed}.keras"),
        "seq_trans":    os.path.join(ART_DIR, f"student_seq_transition_s{seed}.keras"),
    }
import os

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR = os.environ.get("IRP_BASE_DIR", "/iridisfs/home/ao1g22/comp6228/irp")
TFDS_DIR = os.path.join(BASE_DIR, "tfds_data")
ART_DIR  = os.path.join(BASE_DIR, "artifacts_v2")
OUT_DIR  = os.path.join(BASE_DIR, "outputs_v2")

for _d in (ART_DIR, OUT_DIR):
    os.makedirs(_d, exist_ok=True)

# ── Shapes3D ──────────────────────────────────────────────────────────────────
GROUP_FACTORS = ["floor_hue", "wall_hue", "object_hue", "scale", "shape"]
SEQ_FACTOR    = "orientation"
SEQ_LENGTH    = 15

PROBE_FACTORS = {
    "shape":       4,
    "floor_hue":  10,
    "wall_hue":   10,
    "object_hue": 10,
    "scale":       8,
    "orientation": 15,
}

N_TRAIN_GROUPS = 4000
N_TEST_GROUPS  = 1000

# ── Model ─────────────────────────────────────────────────────────────────────
IMG_SHAPE      = (64, 64, 3)
LATENT_DIM     = 32          # teacher frame-level latent dimension
SEQ_LATENT_DIM = 64          # sequence VAE bottleneck dimension
BATCH_SIZE     = 32

# ── Teacher training ──────────────────────────────────────────────────────────
TEACHER_EPOCHS = 40

# ── Student training ──────────────────────────────────────────────────────────
STUDENT_EPOCHS     = 30
STUDENT_KL_WEIGHT  = 1e-4

# Checkpoints saved at these epochs for Exp 2 (semanticisation over time)
CHECKPOINT_EPOCHS  = [5, 10, 20, 30]

# ── IID replay (Spens & Burgess baseline) ─────────────────────────────────────
N_IID_REPLAY  = 8000
BETA_MHN      = 100.0
MHN_NOISE_STD = 0.3

# ── Sequential replay ─────────────────────────────────────────────────────────
N_CHAINS     = 400
CHAIN_LENGTH = 15
BETA_KV      = 60.0
TOPK         = 50

# ── Multi-seed ────────────────────────────────────────────────────────────────
SEEDS = [0, 7, 42]

# ── Artifact paths ────────────────────────────────────────────────────────────
TEACHER_ENC_PATH = os.path.join(ART_DIR, "teacher_encoder.keras")
TEACHER_DEC_PATH = os.path.join(ART_DIR, "teacher_decoder.keras")
K_PATH           = os.path.join(ART_DIR, "K.npy")
V_PATH           = os.path.join(ART_DIR, "V.npy")


def student_paths(seed: int) -> dict:
    s = seed
    return {
        # Sequence VAE — sequential replay (ordered)
        "seq_vae_enc":  os.path.join(ART_DIR, f"seq_vae_encoder_s{s}.keras"),
        "seq_vae_dec":  os.path.join(ART_DIR, f"seq_vae_decoder_s{s}.keras"),
        # Sequence VAE — shuffled ablation (same architecture, random order)
        "shuf_vae_enc": os.path.join(ART_DIR, f"shuf_vae_encoder_s{s}.keras"),
        "shuf_vae_dec": os.path.join(ART_DIR, f"shuf_vae_decoder_s{s}.keras"),
        # Original frame-level IID VAE (Spens & Burgess baseline)
        "iid_enc":      os.path.join(ART_DIR, f"iid_encoder_s{s}.keras"),
        "iid_dec":      os.path.join(ART_DIR, f"iid_decoder_s{s}.keras"),
        # Checkpoint directory for Exp 2
        "seq_ckpt_dir": os.path.join(ART_DIR, f"seq_vae_checkpoints_s{s}"),
    }